apiVersion: extensions/v1beta1
kind: Deployment 
metadata:
  name: openmrs-deploy
spec:
replicas: 3
minReadySeconds: 30
strategy:
  type: RollingUpdate
    maxUnavailable: 1
    maxSurge: 1
template:
  metadata:
  labels:
    app: openrms
  spec:
  containers:
  - name: openmrs
    image: devilnaga/openrms:2.1.2
